/**
 * 导出 / 预览页底部水印（纯文字三栏，无底栏色条）。
 *
 * 设计基准为手机竖屏（1080 宽）；B5 等窄画布按 canvasWidth 等比缩放。
 *
 * 布局（底部 66px transparent 区，仅文字带品牌色；文字带上下各留 22px）：
 *   左：Generated by SHUFURI   中：- N -（绝对居中）   右：shufuri.com
 *
 * 移除旧版右下角「— 01 / 03 —」页码与独立品牌名行，以及 isDemo 的 Demo 小标。
 */
import { dimForProfile, MOBILE_DIM } from './dimensions';
import type { PosterLayoutProfile } from './types';

export const WATERMARK_BRAND = 'SHUFURI';
/** 左栏前缀文案（设计稿定稿前缀改为 Powered by，降低品牌存在感） */
export const WATERMARK_BRAND_PREFIX = 'Powered by ';
/** 右栏域名 */
export const WATERMARK_DOMAIN = 'shufuri.com';

/** 距页面底部（mobile 基准 px） */
export const WATERMARK_BOTTOM_PX = 0;
/** 水印区高度（mobile 基准 px），内部 flex 居中 */
export const WATERMARK_BAR_HEIGHT_PX = 66;
/** 水印文字安全距离（mobile 基准 px）：分页测量时正文底需距 shell 底部至少此值，
 *  确保末行不压到水印文字（约等于水印文字高度 + 小间隙，远小于 BAR_HEIGHT） */
export const WATERMARK_TEXT_CLEARANCE_PX = 22;
/** 左右内边距（mobile 基准 px） */
export const WATERMARK_PAD_H_PX = 28;

/** 品牌字（左/右栏）字号 */
export const WATERMARK_BRAND_FONT_PX = 22;
/** 品牌字距 */
export const WATERMARK_BRAND_LETTER_SPACING_PX = 0.5;
/** 页码字号 */
export const WATERMARK_PAGE_FONT_PX = 16;
/** 页码字距 */
export const WATERMARK_PAGE_LETTER_SPACING_PX = 1;

/** 与 @font-face "Sansation" Regular 对齐 */
export const WATERMARK_FONT_FAMILY = '"Sansation", sans-serif';

/**
 * 水印文字颜色（淡灰，Light 导出主题，无明暗差异）。
 * 终调后进一步降低存在感：品牌字用约 45% 深灰，避免喧宾夺主。
 */
export const WATERMARK_FG_COLOR = 'rgba(43, 43, 43, 0.45)';
/** 页码颜色：同色系更弱（约 30% 深灰） */
export const WATERMARK_PAGE_COLOR = 'rgba(43, 43, 43, 0.3)';

/** 相对手机竖屏画布宽度的缩放（B5 ≈ 600/1080） */
export function watermarkDesignScale(profile: PosterLayoutProfile): number {
  const w = dimForProfile(profile).canvasWidth;
  return w / MOBILE_DIM.canvasWidth;
}

function scaledWatermarkPx(px: number, scale: number): number {
  return Math.max(1, Math.round(px * scale));
}

/** 页码行：- 3 -（hyphen，两侧各一空格） */
export function formatWatermarkPageLabel(pageNumber: number): string {
  const n = Math.max(1, Math.floor(pageNumber));
  return `- ${n} -`;
}

export function buildPosterWatermarkHtml(pageNumber: number): string {
  const page = formatWatermarkPageLabel(pageNumber);
  const brand = `${WATERMARK_BRAND_PREFIX}${WATERMARK_BRAND}`;
  return (
    `<div class="fv-poster-watermark" aria-hidden="true">` +
    `<span class="fv-poster-watermark__brand">${brand}</span>` +
    `<span class="fv-poster-watermark__page">${page}</span>` +
    `<span class="fv-poster-watermark__domain">${WATERMARK_DOMAIN}</span>` +
    `</div>`
  );
}

/** 挂载到海报 shell（导出 DOM） */
export function appendPosterWatermark(
  parent: HTMLElement,
  pageNumber: number,
  doc: Document = document,
): HTMLElement {
  const root = doc.createElement('div');
  root.className = 'fv-poster-watermark';
  root.setAttribute('aria-hidden', 'true');

  const brandEl = doc.createElement('span');
  brandEl.className = 'fv-poster-watermark__brand';
  brandEl.textContent = `${WATERMARK_BRAND_PREFIX}${WATERMARK_BRAND}`;

  const pageEl = doc.createElement('span');
  pageEl.className = 'fv-poster-watermark__page';
  pageEl.textContent = formatWatermarkPageLabel(pageNumber);

  const domainEl = doc.createElement('span');
  domainEl.className = 'fv-poster-watermark__domain';
  domainEl.textContent = WATERMARK_DOMAIN;

  root.appendChild(brandEl);
  root.appendChild(pageEl);
  root.appendChild(domainEl);
  parent.appendChild(root);
  return root;
}

export type WatermarkCssSizeFn = (px: number) => string;

export type BuildPosterWatermarkCssOptions = {
  /** 缺省按 mobile 基准（scale=1） */
  profile?: PosterLayoutProfile;
  /** 用于 px / mm 换算（打印） */
  sizeFn?: WatermarkCssSizeFn;
};

/** 水印样式；B5 等按画布宽度相对 mobile 等比缩小 */
export function buildPosterWatermarkCss(
  options: BuildPosterWatermarkCssOptions | WatermarkCssSizeFn = {},
): string {
  // 兼容旧调用：buildPosterWatermarkCss((px) => `${px}px`)
  const opts: BuildPosterWatermarkCssOptions =
    typeof options === 'function' ? { sizeFn: options } : options;
  const scale = opts.profile ? watermarkDesignScale(opts.profile) : 1;
  const sizeFn = opts.sizeFn ?? ((px: number) => `${px}px`);
  const s = (px: number) => sizeFn(scaledWatermarkPx(px, scale));

  return `
  .fv-poster-watermark {
    position: absolute;
    left: 0;
    right: 0;
    bottom: ${s(WATERMARK_BOTTOM_PX)};
    height: ${s(WATERMARK_BAR_HEIGHT_PX)};
    display: flex;
    align-items: center;
    padding: 0 ${s(WATERMARK_PAD_H_PX)};
    background: transparent;
    pointer-events: none;
    z-index: 3;
  }
  .fv-poster-watermark__brand {
    font-family: ${WATERMARK_FONT_FAMILY};
    font-weight: 400;
    font-size: ${s(WATERMARK_BRAND_FONT_PX)};
    line-height: 1;
    letter-spacing: ${s(WATERMARK_BRAND_LETTER_SPACING_PX)};
    color: ${WATERMARK_FG_COLOR};
  }
  .fv-poster-watermark__page {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    font-family: ${WATERMARK_FONT_FAMILY};
    font-weight: 400;
    font-size: ${s(WATERMARK_PAGE_FONT_PX)};
    line-height: 1;
    letter-spacing: ${s(WATERMARK_PAGE_LETTER_SPACING_PX)};
    color: ${WATERMARK_PAGE_COLOR};
  }
  .fv-poster-watermark__domain {
    margin-left: auto;
    font-family: ${WATERMARK_FONT_FAMILY};
    font-weight: 400;
    font-size: ${s(WATERMARK_BRAND_FONT_PX)};
    line-height: 1;
    letter-spacing: ${s(WATERMARK_BRAND_LETTER_SPACING_PX)};
    color: ${WATERMARK_FG_COLOR};
  }`;
}
