import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const jpOtfPath = path.join(root, 'public/assets/KozMinPro-ExtraLight.otf');
const outPath = path.join(root, 'src/utils/vectorPrint/printFontBase64.generated.ts');

const jpBase64 = fs.readFileSync(jpOtfPath).toString('base64');

const content = `/** Auto-generated by scripts/generatePrintFontBase64.mjs — do not edit */
export const PRINT_JP_FONT_BASE64_GENERATED = ${JSON.stringify(jpBase64)};
/** @deprecated 使用 PRINT_JP_FONT_BASE64_GENERATED */
export const PRINT_FONT_BASE64_GENERATED = PRINT_JP_FONT_BASE64_GENERATED;
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(
  `Wrote ${outPath} (JP ${(jpBase64.length / 1024 / 1024).toFixed(2)} MB base64)`,
);
