import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const jpOtfPath = path.join(root, 'public/assets/KozMinPro-ExtraLight.otf');
const koTtfPath = path.join(root, 'public/assets/HCRBatang.ttf');
const enTtfPath = path.join(root, 'public/assets/Sansation-Light.ttf');
const outPath = path.join(root, 'src/utils/vectorPrint/printFontBase64.generated.ts');

const jpBase64 = fs.readFileSync(jpOtfPath).toString('base64');

let koBase64 = '';
if (fs.existsSync(koTtfPath)) {
  koBase64 = fs.readFileSync(koTtfPath).toString('base64');
}

let enBase64 = '';
if (fs.existsSync(enTtfPath)) {
  enBase64 = fs.readFileSync(enTtfPath).toString('base64');
}

const content = `/** Auto-generated by scripts/generatePrintFontBase64.mjs — do not edit */
export const PRINT_JP_FONT_BASE64_GENERATED = ${JSON.stringify(jpBase64)};
export const PRINT_KO_FONT_BASE64_GENERATED = ${JSON.stringify(koBase64)};
export const PRINT_EN_FONT_BASE64_GENERATED = ${JSON.stringify(enBase64)};
/** @deprecated 使用 PRINT_JP_FONT_BASE64_GENERATED */
export const PRINT_FONT_BASE64_GENERATED = PRINT_JP_FONT_BASE64_GENERATED;
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(
  `Wrote ${outPath} (JP ${(jpBase64.length / 1024 / 1024).toFixed(2)} MB, KO ${koBase64 ? (koBase64.length / 1024 / 1024).toFixed(2) + ' MB' : 'N/A'}, EN ${enBase64 ? (enBase64.length / 1024).toFixed(0) + ' KB' : 'N/A'} base64)`,
);
